### ISSUE TITLE
peer.connectID is 0 when it's an ENET_EVENT_TYPE_DISCONNECT event

### ISSUE THREAD

**Issue by Ohmnivore** [snowkit/linc_enet#2]
I'm using ENetPeer's connectID to keep track of who is who in my server code, and it stays consistent, but it becomes 0 when I handle a disconnection event. Code below (issue arrises in the ENetEventType.ENET_EVENT_TYPE_DISCONNECT case). I suspect the peer/event is deleted in the c code before it reaches the Haxe wrappers or something...

```
        var event:ENetEvent = null;
        var eventStatus:Int = ENet.host_service(host, cast event, 0);
        if (eventStatus > 0)
        {
            var peer = event.peer; 
            var adress = peer.address; 
            var host = adress.host;
            switch(event.type)
            {
                case ENetEventType.ENET_EVENT_TYPE_CONNECT:
                    peers.set(peer.connectID, peer);
                    connected = true;
                    if (onConnect != null)
                        onConnect(Std.int(peer.connectID));
                case ENetEventType.ENET_EVENT_TYPE_DISCONNECT:
                    peers.remove(peer.connectID);
                    if (onDisconnect != null)
                        onDisconnect(Std.int(peer.connectID));
```

**Comment by Ohmnivore** [comment]
Oh wait just read the enet docs they say it's supposed to be that way

**Comment by Ohmnivore** [comment]
The docs say that on a disconnect event only peer.data is valid, so I've been trying to set it to the connectID when the client connects, and to retrieve it later when he disconnects, but I can't figure out how to do it with the cpp.Pointer api.

**Comment by dazKind** [comment]
You could try the following:

```
// packing: 
var id:Int = Std.int(peer.connectID);
peer.data = cast cpp.Pointer.addressOf(id); // im not sure if cpp.Pointer will keep the original var alive(gc). Gotta test it.
```

```
// unpacking
var id:Int = cast peer.data.get_ref();
```

**Comment by Ohmnivore** [comment]
Thanks for the quick reply! The cpp pointer is still driving me nuts though.

If I do

```
var id:Int = Std.int(peer.connectID);
peer.data = cast cpp.Pointer.addressOf(id);
trace(peer.data);
```

it outputs

```
Pointer(00000000)
```

Casting the pointer's ref or value like below gives cpp compilation errors and says it can't cast type void\* to anything else. Not casting it will also not work because then id becomes of type Void and the Haxe compiler complains when i do trace(id) or something.

```
var id:Int = cast peer.data.get_ref();
```

**Comment by Ohmnivore** [comment]
I think a possible solution would be to add a convenience function to the c source which returns a peer's data as a Haxe "value" type object. So, the void\* to value conversion would be written in the c source, and not generated by hxcpp.

**Comment by Ohmnivore** [comment]
I came up with a workaround solution to the problem. It's really really ugly though. My pointer skills aren't the best but I think what this code does is:
1) set_peer_data_from_connect_id: sets the peer's data's address to the value of the peer's connectID
2) get_peer_data_as_int: returns the address of the peer's data as an int

So it uses the data pointer as an int field. That's pretty ugly, and I also hate patching ENet's source code directly, but it works as a temporary solution...

enet/ENet.hx

```
// Get data on disconnect workaround
@:native("::set_peer_data_from_connect_id")
static function set_peer_data_from_connect_id (_peer:ENetPeerRef):Void;
@:native("::get_peer_data_as_int")
static function get_peer_data_as_int (_peer:ENetPeerRef):Int;
```

lib/enet/include/enet/enet.h

```
ENET_API void set_peer_data_from_connect_id (ENetPeer* p);
ENET_API int get_peer_data_as_int (ENetPeer* p);
```

lib/enet/src/win32.c and lib/enet/src/unix.c

```
void
set_peer_data_from_connect_id (ENetPeer* p)
{
    p->data = p->connectID;
}
int
get_peer_data_as_int (ENetPeer* p)
{
    return (int)p->data;
}
```

**Comment by ruby0x1** [comment]
No library modifications would be committed here or native-toolkit side :)
When wrapping the library, the linc_enet.cpp file is specifically an available wrapper/space to put transformations. If there's some sort of data transform that isn't working directly in haxe for whatever reason, you should facilitate it from the linc c++ side, and definitely shouldn't be monkey patching the data structures outside of the ENet usage patterns. It's 100% unreliable to do so, so let's figure out what the actual problem is you're facing.

I can't actually deduce anything clearly specific from above, to suggest solutions.
My suggestion is to make a small isolated test case that demonstrates what you're trying to do, then it would probably take a couple minutes for us to have a look and know what's happening.

For taking the pointer of a haxe variable you can try `cpp.Pointer.fromHandle(id)`, and if you're worried about GC (but I think this will deal with the reference count) use `cpp.vm.GC.doNoKill`.

**Comment by Ohmnivore** [comment]
I never intended that monkey patch to be in the repo. I cringe when i see it too, but I thought it's still useful as a temp solution for anyone else looking for a fix.

For actual source code, I think this illustrates the problem well:

In test/Server.hx,

```
case ENetEventType.ENET_EVENT_TYPE_DISCONNECT:

                        var peerID:Int = peer.connectID;
                        trace('$host disconnected from Server');
```

would be the obvious way to manage connections. However, by the time the event is passed to the switch connectID has been "GC'd". This is also specified by the ENet docs: only the peer's data field is still accessible when the event is a disconnection. This is the example from its Tutorial page:

```
ENetEvent event;
/* Wait up to 1000 milliseconds for an event. */
while (enet_host_service (client, & event, 1000) > 0)
{
    switch (event.type)
    {
    case ENET_EVENT_TYPE_CONNECT:
        printf ("A new client connected from %x:%u.\n", 
                event.peer -> address.host,
                event.peer -> address.port);
        /* Store any relevant client information here. */
        event.peer -> data = "Client information";
        break;
    case ENET_EVENT_TYPE_RECEIVE:
        printf ("A packet of length %u containing %s was received from %s on channel %u.\n",
                event.packet -> dataLength,
                event.packet -> data,
                event.peer -> data,
                event.channelID);
        /* Clean up the packet now that we're done using it. */
        enet_packet_destroy (event.packet);

        break;

    case ENET_EVENT_TYPE_DISCONNECT:
        printf ("%s disconnected.\n", event.peer -> data);
        /* Reset the peer's client information. */
        event.peer -> data = NULL;
    }
}
...
...
...

```

So, the actual implementation is:
1) On connect, store the peer's connectID in the peer's data field
2) On disconnect, read the peer's data field instead of connectID

I've been trying to make that happen in Haxe but I've tried all the obvious Pointer functions, it still won't work. There's no documentation about the Haxe cpp.Pointer class so I'm in the dark.

For step 1 I'm using

```
var peerIDProxy:Int = Std.int(peer.connectID);
peer.data = cpp.Pointer.fromHandle(peerIDProxy, "int");
```

I have no way to know if it works yet because I just can't get step 2 to work.

I tried

```
var connectID:Int = cast peer.data.get_ref();
```

and many other variations, but inevitably it comes to this:

```
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/linc_enet/git//lib/ -IC:/HaxeToolkit/haxe/lib/linc_enet/git//linc/ -IC:/HaxeToolkit/haxe/lib/linc_enet/git/lib//enet/include/ -DNATIVE_TOOLKIT_ENET -nologo -Od /WX- /fp:precise -DHX_WINDOWS -D_USING_V120_SDK71_ -GR -Zi -Fdobj/msvc18-debug-ncxp/vc.pdb -FS -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,2,193/include -DHXCPP_DEBUG -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN -wd4996 -MT ./src/chopnet/net/NetENet.cpp -FoC:/Users/Ohmnivore/Desktop/HAXEDEV/Multijump/exportserver/windows/cpp/obj/obj/msvc18-debug-ncxp/05c04eec_NetENet.obj
NetENet.cpp
./src/chopnet/net/NetENet.cpp(208) : error C2228: left of '.Cast' must have class/struct/union
        type is 'void *'
./src/chopnet/net/NetENet.cpp(208) : error C2059: syntax error : ')'
```

where line 208 of NetENet.cpp is:

```
int connectID = ((int)(peer->data.Cast< ::cpp::Pointer< Void > >()->get_ref()));        HX_STACK_VAR(connectID,"connectID");
```

No matter what hxcpp insists on adding the .Cast to the expression.

**Comment by ruby0x1** [comment]
Remember that the features stem from c++, here. 
A lot of the self-documenting nature of this API is based on existing understanding of c++ first. 
Without a clear picture I can easily understand why this stuff can be obscure seeming, it's a normal side effect of using C++ :p

That's not to say that examples and documentation aren't needed, but that largely these patterns are not documenting haxe, but would be documenting understanding c++, and then the examples in context may be based on that.

Sometimes you can find good examples in the [test folder](https://github.com/HaxeFoundation/hxcpp/tree/master/test),
 (these are a wip and are being expanded all the time).

For this:
`peer.data = cpp.Pointer.fromHandle(peerIDProxy);`
The [second arg is optional](http://api.haxe.org/cpp/Pointer.html#fromHandle)

And on the next one, you don't want the _reference_, you want the value back. 
(this is the c++ understanding).

`var connectID:Int = cast peer.data.get_value();`

Try that, but to add:
The reason I suggested an isolated test is because we are trying to debug text, and not code. 
We'll have to wade through all of your assumptions first, and we still only see the partial view of the situation through how you perceive it, and what you consider most relevant. There are things missing that we'd need to see, which incurs a lot of roundabout.

To get the most direct answer, give us something we can actually build, run, and debug.
There is no way we can view all of the output code, the input code etc reasonably without it.

**Comment by Ohmnivore** [comment]
Here's a slightly modified version of linc_enet/test/Server.hx that shows what i'm trying to do: https://gist.github.com/Ohmnivore/b2c0ba25270f9a1415c6#file-server-hx

C++ is mind-boggling. It's true though that the average Haxe user never has to interact with that part of the Haxe API so the scarcity of documentation is understandable since the rare people who do use it have their cpp basics on point xD

**Comment by dazKind** [comment]
wow, I somehow missed out on this discussion. 

Anyway, I'm sure there could be a way to extend some functionality/wrappers on the binding level like we did with byte-handling of the packet(e.g. https://github.com/snowkit/linc_enet/blob/master/enet/ENet.hx#L156) to make things more convenient. I'll have a look.

**Comment by dazKind** [comment]
Ok, I got it to work, but Sven will cringe a bit eventually. But nevertheless a worthwhile addition for further discussion. Please note, I only tested this with a server and a single client!

I forked your gist and made some modifications: https://gist.github.com/dazKind/52217cad37c3e55ba6c8
I changed the peer-map to hold a dynamic and then I hand over the pointer of the dynamic to peer.data.

But that will only work if we change the binding in https://github.com/snowkit/linc_enet/blob/master/enet/ENet.hx#L271 and make it 
`var data:cpp.RawPointer<cpp.Void>;`

**Comment by Ohmnivore** [comment]
Awesome! I'll test later today with a few clients.

**Comment by Ohmnivore** [comment]
I'm using it with a HaxeFlixel application, and it looks like there's some garbage collection issues. trace(data.get_ref()) gives me the toString() of completely unrelated objects (FlxObjects, my own classes, etc.)

Works fine with the default test though, so it's not just my machine acting weirdly.

**Comment by dazKind** [comment]
OK, that's bad. 

I updated my gist https://gist.github.com/dazKind/52217cad37c3e55ba6c8 with another working idea.

It still needs the aforementioned modification of ENet.hx which should be completely safe now.

I used codeinjection and a little extern to bypass gc completely. Ofc you need to make sure this wont leak anywhere but this could actually work! :P

**Comment by Ohmnivore** [comment]
Works perfectly. Thank you!

**Comment by dazKind** [comment]
Using the same approach in my project now and it works like a charm. The type has officially changed now, too (see https://github.com/snowkit/linc_enet/commit/86717830b3a3c0bf88f1097eadd3dc4e3cc144f0).

:+1:
